find_package(PCL REQUIRED)
#find_package(PCL 1.11)
list(REMOVE_ITEM PCL_LIBRARIES "vtkproj4")
message(PCL_INCLUDE_DIRS ${PCL_INCLUDE_DIRS})
message(PCL_LIBRARIES ${PCL_LIBRARIES})
link_directories(${PCL_LIBRARY_DIRS})
#add_definitions(${PCL_DEFINITIONS})
include_directories(${PCL_INCLUDE_DIRS})
list(APPEND ALL_TARGET_LIBRARIES ${PCL_LIBRARIES})